apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: dalston
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-persistence-volume
        emptyDir: {}
      containers:
      - image: mysql:8.0
        name: mysql
        resources: {}
        volumeMounts:
        - name: mysql-persistence-volume
          mountPath: /docker-entrypoint-initdb.d
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: MYSQL_SERVICE_HOST
            value: "pages-mysql"
          - name: MYSQL_SERVICE_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: "pages"
          - name: MYSQL_USER
            value: "root"

status: {}
