apiVersion: v1
kind: Service
metadata:
  labels:
    app: pages
    tier: database
  name: pages-mysql
  namespace: dalston
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: pages
    tier: database
status:
  loadBalancer: {}
